// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: warlock.proto

package warlockpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MatcherService_SubmitOrder_FullMethodName   = "/warlock.v1.MatcherService/SubmitOrder"
	MatcherService_CancelOrder_FullMethodName   = "/warlock.v1.MatcherService/CancelOrder"
	MatcherService_GetOrderBook_FullMethodName  = "/warlock.v1.MatcherService/GetOrderBook"
	MatcherService_StreamMatches_FullMethodName = "/warlock.v1.MatcherService/StreamMatches"
	MatcherService_HealthCheck_FullMethodName   = "/warlock.v1.MatcherService/HealthCheck"
)

// MatcherServiceClient is the client API for MatcherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatcherServiceClient interface {
	// SubmitOrder submits a new order to the matching engine
	SubmitOrder(ctx context.Context, in *SubmitOrderRequest, opts ...grpc.CallOption) (*SubmitOrderResponse, error)
	// CancelOrder cancels an existing order
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
	// GetOrderBook retrieves the current order book for a token pair
	GetOrderBook(ctx context.Context, in *GetOrderBookRequest, opts ...grpc.CallOption) (*GetOrderBookResponse, error)
	// StreamMatches streams match events in real-time
	StreamMatches(ctx context.Context, in *StreamMatchesRequest, opts ...grpc.CallOption) (MatcherService_StreamMatchesClient, error)
	// HealthCheck verifies the service is running
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type matcherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatcherServiceClient(cc grpc.ClientConnInterface) MatcherServiceClient {
	return &matcherServiceClient{cc}
}

func (c *matcherServiceClient) SubmitOrder(ctx context.Context, in *SubmitOrderRequest, opts ...grpc.CallOption) (*SubmitOrderResponse, error) {
	out := new(SubmitOrderResponse)
	err := c.cc.Invoke(ctx, MatcherService_SubmitOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matcherServiceClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	out := new(CancelOrderResponse)
	err := c.cc.Invoke(ctx, MatcherService_CancelOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matcherServiceClient) GetOrderBook(ctx context.Context, in *GetOrderBookRequest, opts ...grpc.CallOption) (*GetOrderBookResponse, error) {
	out := new(GetOrderBookResponse)
	err := c.cc.Invoke(ctx, MatcherService_GetOrderBook_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matcherServiceClient) StreamMatches(ctx context.Context, in *StreamMatchesRequest, opts ...grpc.CallOption) (MatcherService_StreamMatchesClient, error) {
	stream, err := c.cc.NewStream(ctx, &MatcherService_ServiceDesc.Streams[0], MatcherService_StreamMatches_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &matcherServiceStreamMatchesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MatcherService_StreamMatchesClient interface {
	Recv() (*MatchEvent, error)
	grpc.ClientStream
}

type matcherServiceStreamMatchesClient struct {
	grpc.ClientStream
}

func (x *matcherServiceStreamMatchesClient) Recv() (*MatchEvent, error) {
	m := new(MatchEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *matcherServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, MatcherService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatcherServiceServer is the server API for MatcherService service.
// All implementations must embed UnimplementedMatcherServiceServer
// for forward compatibility
type MatcherServiceServer interface {
	// SubmitOrder submits a new order to the matching engine
	SubmitOrder(context.Context, *SubmitOrderRequest) (*SubmitOrderResponse, error)
	// CancelOrder cancels an existing order
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	// GetOrderBook retrieves the current order book for a token pair
	GetOrderBook(context.Context, *GetOrderBookRequest) (*GetOrderBookResponse, error)
	// StreamMatches streams match events in real-time
	StreamMatches(*StreamMatchesRequest, MatcherService_StreamMatchesServer) error
	// HealthCheck verifies the service is running
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedMatcherServiceServer()
}

// UnimplementedMatcherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMatcherServiceServer struct {
}

func (UnimplementedMatcherServiceServer) SubmitOrder(context.Context, *SubmitOrderRequest) (*SubmitOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitOrder not implemented")
}
func (UnimplementedMatcherServiceServer) CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedMatcherServiceServer) GetOrderBook(context.Context, *GetOrderBookRequest) (*GetOrderBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderBook not implemented")
}
func (UnimplementedMatcherServiceServer) StreamMatches(*StreamMatchesRequest, MatcherService_StreamMatchesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMatches not implemented")
}
func (UnimplementedMatcherServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMatcherServiceServer) mustEmbedUnimplementedMatcherServiceServer() {}

// UnsafeMatcherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatcherServiceServer will
// result in compilation errors.
type UnsafeMatcherServiceServer interface {
	mustEmbedUnimplementedMatcherServiceServer()
}

func RegisterMatcherServiceServer(s grpc.ServiceRegistrar, srv MatcherServiceServer) {
	s.RegisterService(&MatcherService_ServiceDesc, srv)
}

func _MatcherService_SubmitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatcherServiceServer).SubmitOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatcherService_SubmitOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatcherServiceServer).SubmitOrder(ctx, req.(*SubmitOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatcherService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatcherServiceServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatcherService_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatcherServiceServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatcherService_GetOrderBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatcherServiceServer).GetOrderBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatcherService_GetOrderBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatcherServiceServer).GetOrderBook(ctx, req.(*GetOrderBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatcherService_StreamMatches_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMatchesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MatcherServiceServer).StreamMatches(m, &matcherServiceStreamMatchesServer{stream})
}

type MatcherService_StreamMatchesServer interface {
	Send(*MatchEvent) error
	grpc.ServerStream
}

type matcherServiceStreamMatchesServer struct {
	grpc.ServerStream
}

func (x *matcherServiceStreamMatchesServer) Send(m *MatchEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _MatcherService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatcherServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatcherService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatcherServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatcherService_ServiceDesc is the grpc.ServiceDesc for MatcherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatcherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "warlock.v1.MatcherService",
	HandlerType: (*MatcherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitOrder",
			Handler:    _MatcherService_SubmitOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _MatcherService_CancelOrder_Handler,
		},
		{
			MethodName: "GetOrderBook",
			Handler:    _MatcherService_GetOrderBook_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _MatcherService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMatches",
			Handler:       _MatcherService_StreamMatches_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "warlock.proto",
}
